load("//tools:defs.bzl", "go_library")

package(licenses = ["notice"])

go_library(
    name = "izumi",
    srcs = [
        "utils.go",
    ],
    visibility = ["//visibility:public"], 
    deps = [
        "//pkg/log", 
    ],
)